
version: '2'

volumes:
  orderer.cool-network.com:
  peer0.microsoft.cool-network.com:
  peer1.microsoft.cool-network.com:
  peer0.apple.cool-network.com:
  peer1.apple.cool-network.com:
  peer0.ibm.cool-network.com:
  peer1.ibm.cool-network.com:
  peer0.google.cool-network.com:
  peer1.google.cool-network.com:

networks:
  byfn:

services:

  orderer.cool-network.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.cool-network.com
    container_name: orderer.cool-network.com
    networks:
      - byfn

  peer0.microsoft.cool-network.com:
    container_name: peer0.microsoft.cool-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.microsoft.cool-network.com
    networks:
      - byfn

  peer1.microsoft.cool-network.com:
    container_name: peer1.microsoft.cool-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.microsoft.cool-network.com
    networks:
      - byfn

  peer0.apple.cool-network.com:
    container_name: peer0.apple.cool-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.apple.cool-network.com
    networks:
      - byfn

  peer1.apple.cool-network.com:
    container_name: peer1.apple.cool-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.apple.cool-network.com
    networks:
      - byfn

  peer0.ibm.cool-network.com:
    container_name: peer0.ibm.cool-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ibm.cool-network.com
    networks:
      - byfn

  peer1.ibm.cool-network.com:
    container_name: peer1.ibm.cool-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.ibm.cool-network.com
    networks:
      - byfn
      
   peer0.google.cool-network.com:
    container_name: peer0.google.cool-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.google.cool-network.com
    networks:
      - byfn
   peer1.google.cool-network.com:
    container_name: peer1.google.cool-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.google.cool-network.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:x86_64-1.0.0-rc1
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.microsoft.cool-network.com:7051
      - CORE_PEER_LOCALMSPID=MicrosoftMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/microsoft.cool-network.com/peers/peer0.microsoft.cool-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/microsoft.cool-network.com/peers/peer0.microsoft.cool-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/apple.cool-network.com/peers/peer0.apple.cool-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/apple.cool-network.com/users/Admin@apple.cool-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.cool-network.com
      - peer0.microsoft.cool-network.com
      - peer1.microsoft.cool-network.com
      - peer0.apple.cool-network.com
      - peer1.apple.cool-network.com
      - peer0.ibm.cool-network.com
      - peer1.ibm.cool-network.com
      - peer0.google.cool-network.com
      - peer1.google.cool-network.com
    networks:
      - byfn
